# Generated by Django 5.2 on 2025-05-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='new_password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
