# Generated by Django 5.2 on 2025-05-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_new_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
