# Generated by Django 5.2 on 2025-05-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_hourly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='new_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
