# Generated by Django 5.2 on 2025-05-07 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ended_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('duration', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Duration in hours')),
                ('status', models.CharField(choices=[('started', 'Started'), ('finished', 'Finished')], default='started', editable=False, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
        ),
    ]
