# Generated by Django 5.2 on 2025-05-07 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='daily_record',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clocks', to='records.dailyrecord', verbose_name='Daily record of the clock'),
        ),
    ]
