# Generated by Django 5.2 on 2025-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_created_date_task_ended_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ended_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
