# Generated by Django 5.2 on 2025-05-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_ended_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('deactive', 'Deactive'), ('active', 'Active'), ('declined', 'Declined'), ('success', 'Success'), ('failed', 'Failed')], default='active', max_length=50),
        ),
    ]
