# Generated by Django 5.2 on 2025-05-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_duration_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
