# Generated by Django 5.2 on 2025-05-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Duration in hours'),
        ),
    ]
