# Generated by Django 5.2 on 2025-05-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='started_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('deactive', 'Deactive'), ('active', 'Active'), ('declined', 'Declined'), ('success', 'Success'), ('failed', 'Failed')], default='deactive', max_length=50),
        ),
    ]
