# Generated by Django 5.2 on 2025-05-03 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_created_date_alter_task_ended_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(editable=False, max_length=250)),
                ('answer', models.TextField(editable=False)),
                ('task', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Task of the question')),
            ],
        ),
    ]
