# Generated by Django 5.2 on 2025-05-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15, null=True, verbose_name='Total amount in this day'),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15, null=True, verbose_name='Total amount in this month'),
        ),
        migrations.AlterField(
            model_name='yearlyrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15, null=True, verbose_name='Total amount in this year'),
        ),
    ]
