# Generated by Django 5.2 on 2025-05-07 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_dailyrecord_amount_alter_monthlyrecord_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='employee',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee of the Record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyrecord',
            name='employee',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee of the Record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlyrecord',
            name='employee',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee of the Record'),
            preserve_default=False,
        ),
    ]
