# Generated by Django 5.2 on 2025-05-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_dailyrecord_employee_monthlyrecord_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='created_date',
            field=models.DateField(editable=False, null=True),
        ),
    ]
